### ISSUE TITLE
Create visualization hacking guide

### ISSUE THREAD

**Issue by fulldecent** [preziotte/party-mode#18]
Related to #17 

The idea is to make it simple for a third party to come in and add a quick hack visualization.

The next step would be to add a "load" button on the web page. Then we expand the userbase from "people that can clone github and hack" to "people that can play music and choose a visualization from a list".

This is about to be as big as WinAmp was.

**Comment by preziotte** [comment]
sounds good to me :+1:

**Comment by fulldecent** [comment]
Not clear enough how I can help here. 

Was thinking something similar to how https://butterchurnviz.com is documented
