### ISSUE TITLE
Using it?

### ISSUE THREAD

**Issue by Kngrektor** [preziotte/party-mode#3]
So how would one actually use it on its own page without going through the source a hundred times?

**Comment by preziotte** [comment]
Define *use it on its own page*.  This is an app, not a framework or a plugin.

When the app first initializes, an svg element is created (https://github.com/preziotte/party-mode/blob/master/js/main.js#L59), and all visualizations are drawn inside this.  You can use this to your advantage if you're tying to embed this in an existing page.
