### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by torresomar** [preziotte/party-mode#4]
There is no license spec, can anyone use this whether its a personal project or a monetized project?
Thanks!

**Comment by preziotte** [comment]
Thanks for the interest, @torresomar.  I've given party-mode a Creative Commons Attribution-NonCommercial 3.0 License.  https://creativecommons.org/licenses/by-nc/3.0/

For commercial projects please inquire mat.preziotte@gmail.com.

Thank you :)
