### ISSUE TITLE
Unable to get it working with soundcloud

### ISSUE THREAD

**Issue by willemdh** [preziotte/party-mode#6]
Hello,

I tried to get this working with a Soundcloud song, artist and playlist, but it doesn't work (with Chrome)

Grtz

**Comment by preziotte** [comment]
It appears Chrome may have fixed the bug that allowed this feature to exist in the first place :)

From the readme:
>soundcloud integration only working in chrome due to MediaElementSource only supporting same-origin sources in other browsers (http://stackoverflow.com/questions/13958158/why-arent-safari-or-firefox-able-to-process-audio-data-from-mediaelementsource/23202652#23202652)

**Comment by willemdh** [comment]
Ok never mind then. :) Thanks for the response.
