### ISSUE TITLE
soundcloud integration only working in chrome

### ISSUE THREAD

**Issue by fulldecent** [preziotte/party-mode#9]
due to MediaElementSource only supporting same-origin sources in other browsers

See: 
https://stackoverflow.com/questions/13958158/why-arent-safari-or-firefox-able-to-process-audio-data-from-mediaelementsource/23202652#23202652

**Comment by preziotte** [comment]
It seems like this broke in Chrome at some point.  Thanks to http://stackoverflow.com/a/31098370 I have another bandaid:

adding `audio.crossOrigin = "anonymous";` does the trick

**Comment by preziotte** [comment]
see: https://github.com/preziotte/party-mode/commit/ac21affaf605820d9a2c3ff861faf3e5e06d7954

**Comment by fulldecent** [comment]
This seems to be fixed now, closing
